<?php
/**
 * Brand Theme functions and definitions.
 *
 * @package BrandTheme
 */

// ──────────────────────────────────────────────
// Theme Setup
// ──────────────────────────────────────────────

function brand_theme_setup() {
    add_theme_support( 'title-tag' );
    add_theme_support( 'post-thumbnails' );
    add_theme_support( 'html5', array(
        'search-form',
        'comment-form',
        'comment-list',
        'gallery',
        'caption',
        'style',
        'script',
    ) );

    register_nav_menus( array(
        'primary' => __( 'Primary Menu', 'brand-theme' ),
        'footer'  => __( 'Footer Menu', 'brand-theme' ),
    ) );
}
add_action( 'after_setup_theme', 'brand_theme_setup' );

// ──────────────────────────────────────────────
// WooCommerce Support
// ──────────────────────────────────────────────

function brand_theme_woocommerce_setup() {
    add_theme_support( 'woocommerce' );
    add_theme_support( 'wc-product-gallery-zoom' );
    add_theme_support( 'wc-product-gallery-lightbox' );
    add_theme_support( 'wc-product-gallery-slider' );
}
add_action( 'after_setup_theme', 'brand_theme_woocommerce_setup' );

// ──────────────────────────────────────────────
// Widget Areas
// ──────────────────────────────────────────────

function brand_theme_widgets_init() {
    register_sidebar( array(
        'name'          => __( 'Sidebar', 'brand-theme' ),
        'id'            => 'sidebar-1',
        'description'   => __( 'Main sidebar area.', 'brand-theme' ),
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget'  => '</div>',
        'before_title'  => '<h3 class="widget-title">',
        'after_title'   => '</h3>',
    ) );

    register_sidebar( array(
        'name'          => __( 'Footer', 'brand-theme' ),
        'id'            => 'footer-1',
        'description'   => __( 'Footer widget area.', 'brand-theme' ),
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget'  => '</div>',
        'before_title'  => '<h3 class="widget-title">',
        'after_title'   => '</h3>',
    ) );
}
add_action( 'widgets_init', 'brand_theme_widgets_init' );

// ──────────────────────────────────────────────
// Vite Asset Loader
// ──────────────────────────────────────────────

function brand_theme_vite_assets() {
    // Development mode — load from Vite dev server.
    if ( defined( 'VITE_DEV' ) && VITE_DEV ) {
        // Vite client for HMR.
        // phpcs:ignore WordPress.WP.EnqueuedResourceParameters.MissingVersion
        wp_enqueue_script_tag(
            '<script type="module" src="http://localhost:5173/@vite/client"></script>'
        );
        add_action( 'wp_head', function () {
            echo '<script type="module" src="http://localhost:5173/@vite/client"></script>' . "\n";
            echo '<script type="module" src="http://localhost:5173/src/js/app.js"></script>' . "\n";
        } );
        return;
    }

    // Production mode — load from built manifest.
    $manifest_path = get_template_directory() . '/dist/.vite/manifest.json';

    if ( ! file_exists( $manifest_path ) ) {
        return;
    }

    $manifest_content = file_get_contents( $manifest_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
    $manifest         = json_decode( $manifest_content, true );

    if ( ! $manifest ) {
        return;
    }

    $entry = $manifest['src/js/app.js'] ?? null;
    if ( ! $entry ) {
        return;
    }

    $dist_uri = get_template_directory_uri() . '/dist/';

    // Enqueue the main JS bundle.
    wp_enqueue_script(
        'brand-theme-app',
        $dist_uri . $entry['file'],
        array(),
        null, // phpcs:ignore WordPress.WP.EnqueuedResourceParameters.MissingVersion
        true
    );

    // Add type="module" to the script tag.
    add_filter( 'script_loader_tag', function ( $tag, $handle ) {
        if ( 'brand-theme-app' === $handle ) {
            $tag = str_replace( '<script ', '<script type="module" ', $tag );
        }
        return $tag;
    }, 10, 2 );

    // Enqueue CSS files generated by Vite.
    if ( ! empty( $entry['css'] ) ) {
        foreach ( $entry['css'] as $index => $css_file ) {
            wp_enqueue_style(
                'brand-theme-app-' . $index,
                $dist_uri . $css_file,
                array(),
                null // phpcs:ignore WordPress.WP.EnqueuedResourceParameters.MissingVersion
            );
        }
    }
}
add_action( 'wp_enqueue_scripts', 'brand_theme_vite_assets' );
