/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './**/*.php',
    './src/**/*.{js,ts,svelte}',
  ],
  safelist: [
    // WooCommerce classes generated by plugin PHP (not in theme templates).
    'woocommerce-message',
    'woocommerce-error',
    'woocommerce-info',
    'woocommerce-notices-wrapper',
    'wc-empty-cart-message',
    'cart-empty',
    'restore-item',
    'wc-forward',
    'wc-backward',
    'shipping-calculator-button',
    'shipping-calculator-form',
    'woocommerce-shipping-methods',
    'woocommerce-shipping-destination',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#fdf4f0',
          100: '#fbe5dc',
          200: '#f7c8b5',
          300: '#f1a284',
          400: '#ea7250',
          500: '#e5532c',
          600: '#e24411',
          700: '#bb350d',
          800: '#942b10',
          900: '#772611',
          950: '#401007',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
