/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './**/*.php',
    './src/**/*.{js,ts,svelte}',
  ],
  safelist: [
    // WooCommerce classes generated by plugin PHP (not in theme templates).
    'woocommerce-message',
    'woocommerce-error',
    'woocommerce-info',
    'woocommerce-notices-wrapper',
    'wc-empty-cart-message',
    'cart-empty',
    'restore-item',
    'wc-forward',
    'wc-backward',
    'shipping-calculator-button',
    'shipping-calculator-form',
    'woocommerce-shipping-methods',
    'woocommerce-shipping-destination',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
          950: '#450a0a',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
